language: python
sudo: false
python:
    - "2.7"
    - "3.5"
# env:
#     - DJANGO=1.6
#     - DJANGO=1.8
install:
#     - pip install -q Django==$DJANGO
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - pip install coveralls
before_script:
    -  flake8 {{app_name}} --exclude=migrations --ignore=E501,E225
script:
    - python setup.py test
after_success:
    - coveralls
